name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY}}
          port: 22
          script: |
            cd /home/Yuhojae/embitips-app
            ls -al
            scp build/libs/embitipstest-0.0.1-SNAPSHOT.jar yuhojae27@34.64.135.207:/home/Yuhojae/embitips-app
            java -jar /home/Yuhojae/embitips-app/build/libs/embitipstest-0.0.1-SNAPSHOT.jar

#      - name: Setup SSH keys
#        run: |
#          mkdir -p ~/.ssh
#          echo "$SSH_PRIVATE_KEY" > ~/.ssh/gcp_key
#          chmod 600 ~/.ssh/gcp_key
#          echo "Running ssh-keyscan..."  # 디버깅을 위한 메시지
#          ssh-keyscan -H 34.64.135.207 >> ~/.ssh/known_hosts
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}

#      - name: Build and Deploy
#        run: |
#          ./gradlew build
#          ls -al build/libs
#          scp build/libs/embitipstest-0.0.1-SNAPSHOT.jar yuhojae27@34.64.135.207:/home/Yuhojae/embitips-app

